/**
 * The tutorial's photograph: drawn, not taken.
 *
 * ## Why this exists
 *
 * Wave 2 made required-role photographs `getUserMedia`-only with no fallback,
 * because `<input capture>` degrades to a file picker on desktop and the schema
 * has no value meaning "we asked for a camera and got a file browser". That is
 * still the right call and nothing here changes it. Its cost is that the flow
 * dead-ends on any machine without a camera — a laptop in a meeting, a
 * screen-share, a headless browser — and a photograph is most of what the app
 * does, so the flow cannot be shown at all.
 *
 * This is the tutorial branch of D18 reaching the capture lane. It is **not** a
 * fallback for a failed camera. A production `CaptureSession` never calls
 * anything in this file; if its camera fails, the role stays visibly
 * unsatisfied and nothing is written, exactly as before.
 *
 * ## Why this cannot contaminate the record
 *
 * `TutorialImage.capture_source` is `'tutorial_synthetic'`, and that string is
 * **not a member of `CaptureSource`**. So:
 *
 *  - `attachToRole(role, image, ctx)` will not accept a `TutorialImage` — its
 *    parameter is `IntakeImage`, a union of the camera and gallery brands.
 *  - `toPayload` cannot build a `MediaMetaPayload` from one, because that type's
 *    `capture_source` field is `CaptureSource`.
 *  - `writeCaptureLocally` only writes `MediaMetaPayload`.
 *
 * The chain is closed by the compiler at every link. This is the same technique
 * as the gallery/required-role separation and it is strictly stronger, because
 * there the two brands at least share a union.
 *
 * ## Why the image is watermarked in its pixels
 *
 * A badge in the UI is a property of the screen that rendered it. A screenshot
 * of that screen, pasted into an email in 2027, is not. The watermark is burnt
 * into the bytes that are hashed, so the marking travels with the image
 * wherever the image goes and cannot be separated from it.
 */

import type { MediaRole } from '../../../shared/contract/common.js';
import type { ProcessedImage } from '../camera/types.js';
import { processImage, type ProcessOptions } from '../camera/pipeline.js';
import type { TutorialCaptureSource } from '../tutorial-boundary.js';

/** Burnt into every synthetic frame. Short enough to survive a thumbnail. */
export const TUTORIAL_WATERMARK = 'TUTORIAL — NOT FIELD EVIDENCE';

/**
 * What a viewer is told, on screen and in the discarded record. Written once
 * so the wording cannot drift between the badge and the summary.
 */
export const TUTORIAL_NOTICE =
  'Synthetic image generated by the in-app tutorial. Not a photograph, not field evidence, not written to any plan.';

/**
 * An image the tutorial drew.
 *
 * Deliberately not part of `IntakeImage`. See the file header — the
 * incompatibility is the guarantee, not an inconvenience.
 */
export interface TutorialImage extends ProcessedImage {
  readonly capture_source: TutorialCaptureSource;
  readonly watermark_text: string;
  readonly scene: string;
}

/** A rendered frame, before the ordinary downscale/hash pipeline runs on it. */
export interface SyntheticFrame {
  bytes: Uint8Array;
  natural_width: number;
  natural_height: number;
  /** A short human name for what was drawn: `soil core`, `bag label`, … */
  scene: string;
}

/**
 * Draws the frame. Injectable for the same reason `ImageCodec` is: the default
 * needs a canvas, and `npm test` runs in Node.
 */
export interface SyntheticImageSource {
  render(role: MediaRole, index: number): Promise<SyntheticFrame>;
}

/**
 * **The only place `tutorial_synthetic` is minted.**
 *
 * Symmetric with `intakeFromCamera` / `intakeFromGallery`, which each mint
 * their own source in exactly one function in `camera/intake.ts`.
 * `separation.test.ts` scans the tree and fails on a second site.
 *
 * The frame goes through the same `processImage` the real path uses — same
 * 1920 px long edge, same q≈0.72, same SHA-256 over the stored bytes — so the
 * byte counts and dimensions the tutorial shows are the ones a real capture
 * would produce, and the storage-budget arithmetic in v02 §4.4 is what the
 * demo is actually demonstrating.
 */
export async function intakeSyntheticImage(
  frame: SyntheticFrame,
  options: ProcessOptions,
): Promise<TutorialImage> {
  const processed = await processImage(frame.bytes, options);
  return {
    ...processed,
    // A drawn image has no EXIF, in exactly the way a `getUserMedia` frame has
    // none. Left honestly empty rather than fabricated: a tutorial that
    // invented a plausible `GPSLatitude` would be teaching the reader of the
    // record that these values can be invented.
    capture_source: 'tutorial_synthetic',
    watermark_text: TUTORIAL_WATERMARK,
    scene: frame.scene,
  };
}

// ── the default renderer ────────────────────────────────────────────────────

const SCENES: Record<MediaRole, string> = {
  label_photo: 'bag label',
  core_photo: 'soil core',
  site_photo: 'sample site',
  issue_photo: 'issue',
  other: 'other',
};

/**
 * `OffscreenCanvas`, which every browser the crew or a reviewer will run has,
 * and which a headless Chromium has too — that last part is the point.
 *
 * Throws rather than degrading if there is no canvas. An unmarked tutorial
 * image is worse than no tutorial image, and a silent fallback is how one gets
 * produced.
 */
export function canvasSyntheticImages(
  options: { width?: number; height?: number } = {},
): SyntheticImageSource {
  // Larger than the 1920 px long edge on purpose, so the demo shows the
  // downscale actually happening rather than a no-op.
  const width = options.width ?? 2400;
  const height = options.height ?? 1800;

  return {
    async render(role: MediaRole, index: number): Promise<SyntheticFrame> {
      if (typeof OffscreenCanvas === 'undefined') {
        throw new Error(
          'tutorial images need OffscreenCanvas; refusing to produce an unwatermarked image',
        );
      }
      const canvas = new OffscreenCanvas(width, height);
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('tutorial images need a 2d context');

      drawScene(ctx as unknown as CanvasRenderingContext2D, role, width, height, index);
      drawWatermark(ctx as unknown as CanvasRenderingContext2D, width, height);

      const blob = await canvas.convertToBlob({ type: 'image/jpeg', quality: 0.9 });
      return {
        bytes: new Uint8Array(await blob.arrayBuffer()),
        natural_width: width,
        natural_height: height,
        scene: SCENES[role],
      };
    },
  };
}

/**
 * Recognisably the right *kind* of picture and unmistakably not a photograph.
 *
 * Flat colour and hard edges, no attempt at photorealism. Someone watching the
 * demo should be able to say what the tile is for without ever thinking they
 * are looking at a field.
 */
function drawScene(
  ctx: CanvasRenderingContext2D,
  role: MediaRole,
  w: number,
  h: number,
  index: number,
): void {
  ctx.fillStyle = '#f8f3ea';
  ctx.fillRect(0, 0, w, h);

  if (role === 'core_photo') {
    // Horizons, dark to light with depth, and a rule down the side.
    const bands = ['#3b2a1c', '#4b3623', '#5d452e', '#75593c', '#8d7150'];
    const top = h * 0.12;
    const usable = h * 0.74;
    bands.forEach((colour, i) => {
      ctx.fillStyle = colour;
      ctx.fillRect(w * 0.3, top + (usable / bands.length) * i, w * 0.4, usable / bands.length);
    });
    ctx.fillStyle = '#132719';
    ctx.fillRect(w * 0.74, top, 10, usable);
    ctx.font = `${Math.round(h * 0.035)}px sans-serif`;
    ctx.fillStyle = '#132719';
    for (let cm = 0; cm <= 30; cm += 10) {
      const y = top + (usable * cm) / 30;
      ctx.fillRect(w * 0.74, y, w * 0.05, 6);
      ctx.fillText(`${cm} cm`, w * 0.8, y + h * 0.012);
    }
  } else if (role === 'label_photo') {
    // A bag with a barcode-shaped block. Not a scannable code — a tutorial
    // image that scanned would be a tutorial image someone could use.
    ctx.fillStyle = '#e6ddcb';
    ctx.fillRect(w * 0.14, h * 0.16, w * 0.72, h * 0.66);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(w * 0.2, h * 0.24, w * 0.6, h * 0.34);
    ctx.fillStyle = '#132719';
    let x = w * 0.24;
    for (let i = 0; x < w * 0.76; i += 1) {
      const bar = 4 + ((i * 7 + index * 3) % 5) * 4;
      ctx.fillRect(x, h * 0.28, bar, h * 0.16);
      x += bar + 6 + ((i * 5) % 4) * 3;
    }
    ctx.font = `${Math.round(h * 0.05)}px sans-serif`;
    ctx.fillText('MODEL LABEL — NOT A REAL BARCODE', w * 0.22, h * 0.52);
  } else {
    // Sky, horizon, field. A site photograph reduced to the three bands that
    // make it read as one.
    ctx.fillStyle = '#bcd6e8';
    ctx.fillRect(0, 0, w, h * 0.42);
    ctx.fillStyle = '#7d8f5a';
    ctx.fillRect(0, h * 0.42, w, h * 0.16);
    ctx.fillStyle = '#6b5b3e';
    ctx.fillRect(0, h * 0.58, w, h * 0.42);
    ctx.fillStyle = '#4b3f2b';
    for (let i = 0; i < 14; i += 1) {
      ctx.fillRect(0, h * 0.6 + i * (h * 0.03), w, 3);
    }
  }
}

/** Diagonal repeats plus a banner, so a crop cannot lose the marking. */
function drawWatermark(ctx: CanvasRenderingContext2D, w: number, h: number): void {
  ctx.save();
  ctx.globalAlpha = 0.34;
  ctx.fillStyle = '#8a1f1f';
  ctx.font = `bold ${Math.round(h * 0.05)}px sans-serif`;
  ctx.translate(w / 2, h / 2);
  ctx.rotate(-Math.PI / 9);
  for (let row = -4; row <= 4; row += 1) {
    ctx.fillText(TUTORIAL_WATERMARK, -w * 0.7, row * (h * 0.16));
    ctx.fillText(TUTORIAL_WATERMARK, w * 0.05, row * (h * 0.16) + h * 0.08);
  }
  ctx.restore();

  ctx.fillStyle = '#8a1f1f';
  ctx.fillRect(0, 0, w, h * 0.09);
  ctx.fillRect(0, h * 0.91, w, h * 0.09);
  ctx.fillStyle = '#ffffff';
  ctx.font = `bold ${Math.round(h * 0.05)}px sans-serif`;
  ctx.fillText(TUTORIAL_WATERMARK, w * 0.03, h * 0.065);
  ctx.fillText('EXAMPLE DATA — DISCARDED ON EXIT', w * 0.03, h * 0.975);
}
